title: "PriorityCut: Occlusion-guided Regularization for Warp-based Image Animation"
description: "Authors: Wai Ting Cheung, Gyeongsu Chae <br><font size='1'></font>ArXiv: <a href='https://arxiv.org/abs/2103.11600'>arXiv:2103.11600</a>"
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
